api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths:
            - '%kernel.project_dir%/src/Books/Infrastructure'
            - '%kernel.project_dir%/src/Auth/Infrastructure'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    collection:
        pagination:
            page_parameter_name: page