services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Auth\Domain\:
        resource: '../../../src/Auth/Domain/'

    Auth\Application\:
        resource: '../../../src/Auth/Application/'

    Auth\Infrastructure\:
        resource: '../../../src/Auth/Infrastructure/'

    security.client_provider:
        class: Auth\Infrastructure\Api\Security\ClientProvider

    Auth\Infrastructure\Api\Security\Authenticator\RsaTokenEncrypter:
        arguments:
            $publicKey: '%env(resolve:JWT_PUBLIC_KEY)%'
            $privateKey: '%env(resolve:JWT_SECRET_KEY)%'
