services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SharedKernel\Framework\:
        resource: '../../../src/SharedKernel/Framework/'

    SharedKernel\Application\Bus\QueryBus:
        class: 'SharedKernel\Framework\Messenger\Bus\MessengerQueryBus'
        arguments: ['@query.bus']
